Agora	Da	Fez	Muito	Pra	Seu	Contra
Alckmin	De	Foi	Na	Que	Só	Mesmo
Alguém	Diz	Geraldo	Nada	Quem	Sobr	Por
Ao	Dos	Geraldoalckmin	Nos	Quer	Sua	Ser
Até	Ele	Hoje	Os	Roda	Tá	Uma
Bem	Em	Isso	Ou	Rodaviva	Tem	Vai
Co	Entr	Já	Para	Rt	Ter	Viva
Com	Ess	Ma	Paulo	São	Todo	Você
Como	Está	Mais	Pela	Sem	Um	Eu
